// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"VoiceRPG_Native","status":true,"description":"Voice RPG Native v2.3.4 - 多策略优化版","parameters":{"enableDebug":"true","autoStart":"false","defaultProvider":"auto","turboMode":"true","partialConfidenceThreshold":"0.8","commandCooldown":"200"}},
{"name":"VoiceRecognitionAdapter","status":true,"description":"Voice Recognition Adapter v2.0.2 - 完整修复版","parameters":{"enableAutoSelect":"true","forceProvider":"auto"}},
{"name":"SpellLearning","status":true,"description":"Spell Learning System v1.0.0 - 咒语学习系统","parameters":{}},
{"name":"SpellAutoInit","status":true,"description":"Spell Auto Initialize v1.0.0 - 咒语自动初始化","parameters":{"autoLearnOnStart":"true","autoLearnOnBattle":"true","basicSpells":"destiny_draw,evil_eye,dragon_roar,normal_attack"}},
{"name":"Scene_Battle_Spell","status":true,"description":"Battle Spell Integration v1.3.4 - 战斗咒语集成（完整修复版）","parameters":{"replaceAttack":"true","showSpellCommand":"true","spellCommandName":"咒语"}},
{"name":"Scene_VoiceConfig","status":true,"description":"Voice Config Scene v2.2.0 - 耳返测试增强版（含音量校准）","parameters":{"showOnFirstStart":"true","defaultProvider":"auto","enableEarback":"true","earbackVolume":"70"}},
{"name":"Scene_VoiceCalibration","status":true,"description":"Voice Calibration Scene v4.0.0 - 音量校准场景（真实版）","parameters":{"skipable":"true","sampleDuration":"3"}},
{"name":"EnemyHPBar","status":true,"description":"Enemy HP Bar v1.1.0 - 敌人血条显示（修复版）","parameters":{"barWidth":"100","barHeight":"8","barOffsetY":"-10","showName":"true","showNumbers":"true","alwaysShow":"true","fadeOutTime":"500"}},
{"name":"ActionSEOnEquip","status":true,"description":"[v1.0] 装备后：我方角色每次行动结束自动播放SE（普攻/技能皆可）","parameters":{"DefaultSEName":"02 打铁声","DefaultVolume":"90","DefaultPitch":"100","DefaultPan":"0"}},
{"name":"TurnSEByInventory","status":true,"description":"[v1.0] 背包里有某道具时，每个战斗回合自动播放SE（可设间隔/可选叠加）","parameters":{"DefaultSEName":"Bell1","DefaultVolume":"90","DefaultPitch":"100","DefaultPan":"0"}},
{"name":"NormalAttackOnly1","status":true,"description":"[v1.3 Lite] 普通攻击→打带<NormalOne>的Boss：结算与所有显示均=1；不依赖全局 SpellSystem","parameters":{}},
{"name":"NormalAttackOnly1_UIFix","status":true,"description":"[v2.1] “普通攻击”打带<NormalOne>的Boss：只本次伤害=1（结算/弹字/消息/结果窗全一致）。标记绑定在本次 result 上，绝不污染后续技能。","parameters":{}},
{"name":"MousseItemEffect","status":true,"description":"持有特定道具时，每回合消耗1000金币并触发慕斯药剂效果","parameters":{"ItemID":"49"}},
{"name":"ItemMultiPing","status":true,"description":"物品备注：回合末多次打击，90%敌方 / 10%我方随机（<MultiPing:H,D>）","parameters":{"delayFrames":"2","allyHitPercent":"10"}},
{"name":"Community_Lighting_MZ","status":true,"description":"v4.6 Creates an extra layer that darkens a map and adds lightsources! Released under the MIT license!","parameters":{"---General Settings---":"","Options Menu Entry":"Lighting Effects","Light event required":"true","Shift lights with events":"false","Daynight Cycle":"true","Reset Lights":"true","Kill Switch":"None","Kill Switch Auto":"false","Note Tag Key":"cl","---DayNight Settings---":"","Daynight Initial Speed":"5","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Save Night Switch":"0","No Autoshadow During Night":"false","Night Hours":"0, 1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23","DayNight Colors":"[\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#9999ff\",\"#ccccff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffcc88\",\"#9999ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\"]","Daynight Initial Hour":"6","---Offset and Sizes---":"","Lights Active Radius":"0","Player radius":"200","Flashlight offset":"0","Flashlight X offset":"0","Screensize X":"1920","Screensize Y":"1080","Lightmask Padding":"32","---Battle Settings---":"","Battle Tinting":"false","Light Mask Position":"Above"}}
];
